fix for case insensitive licenses + auto-completion by usage of enums
ioBroker/ioBroker.js-controller pull request #1258
Opened 2021-03-09 10:10 UTC by foxriver76

2021-03-09 10:28 UTC, AlCalzone requested changes

2021-03-09 10:28 UTC, AlCalzone commented on schemas/io-package.json
> +                            "pattern": "[a|A][r|R][t|T][i|I][s|S][t|T][i|I][c|C]-2.0|[a|A][p|P][a|A][c|C][h|H][e|E]-2.0|[p|P][o|O][s|S][t|T][g|G][r|R][e|E][s|S][q|Q][l|L]|[u|U][n|N][l|L][i|I][c|C][e|
```suggestion
                            "pattern": "[a|A][r|R][t|T][i|I][s|S][t|T][i|I][c|C]-2.0|[a|A][p|P][a|A][c|C][h|H][e|E]-2.0|[p|P][o|O][s|S][t|T][g|G][r|R][e|E][s|S][q|Q][l|L]|[u|U][n|N][l|L][i|I][c|C][e|E][n|N][s|S][e|E]",
```

2021-03-09 10:28 UTC, AlCalzone commented on schemas/io-package.json
> +                        }
I would just add another enum value `Apache-2.0`, `PostgreSQL` and `Unlicense` instead.

2021-03-09 11:22 UTC, AlCalzone approved these changes

2021-03-11 09:54 UTC, foxriver76 commented
https://github.com/SchemaStore/schemastore/pull/1506

2021-03-11 09:55 UTC, merged