rm adapter objects dummies
ioBroker/ioBroker.js-controller pull request #1513
Opened 2021-11-04 13:44 UTC by foxriver76

- closes #770

2021-11-04 13:45 UTC, foxriver76 commented
@Apollon77 please grep first if still used anywhere

2021-11-05 10:05 UTC, AlCalzone requested changes
We should think about making `this.aliases` a `Map` which allows for more performant accesses/length checks

2021-11-05 10:05 UTC, AlCalzone commented on packages/adapter/lib/adapter/adapter.js
>                          const alias = this.aliases[sourceId];
```suggestion
                    for (const [sourceId, alias] of Object.entries(this.aliases)) {
```

2021-11-05 10:05 UTC, AlCalzone commented on packages/adapter/lib/adapter/adapter.js
> +                for (const sourceId of Object.keys(this.aliases)) {
Same here, this also avoids repeating `this.aliases[sourceId]`.

2021-11-05 10:23 UTC, AlCalzone commented
For some benchmarks:

even for small objects (100 entries), map.size is ~4x faster than Object.keys(...).length:
https://jsben.ch/CLIVp

bump the size up to 100000 and map.size is ~12000x faster
https://jsben.ch/6WZsu

Iterating looks like this map > Object.keys >> Object.entries
(actually the last bit is suprising)
https://jsben.ch/XG63T

Element access is approx. equal

2021-11-05 10:28 UTC, foxriver76 commented
MAkes sense to switch for me. But lets not do it in this PR, there are already some unrelated code changes 😄

2021-11-05 10:28 UTC, AlCalzone commented
There are probably a **BUNCH** of locations where a map would be beneficial.

2021-11-06 00:03 UTC, Apollon77 commented
LGTM

2021-11-14 16:49 UTC, merged