Corrected aliases error output and added IDs of the problem objects
ioBroker/ioBroker.js-controller pull request #2061
Opened 2022-12-15 23:04 UTC by GermanBluefox

If target or source does not exist in aliases, function formatAliasValue crashed, but did not show the problem objects.
This PR corrects it.

2022-12-16 20:38 UTC, Apollon77 requested changes
Just some small stuff in texts and logging from my side

2022-12-16 20:38 UTC, Apollon77 commented on packages/common/src/lib/common/tools.ts
> +                `${logNamespace} source in "${targetId}" not exist for "read" function: "${targetObj.alias.read}"`
```suggestion
                `${logNamespace}source in "${targetId}" does not exist for "read" function: "${targetObj.alias.read}"`
```

2022-12-16 20:38 UTC, Apollon77 commented on packages/common/src/lib/common/tools.ts
> +                `${logNamespace} source in "${targetId}" not exist for "read" function: "${targetObj.alias.read}"`
And formally the "space too much after ${logNamespace} needs to be changed in whole function :-)

2022-12-16 20:38 UTC, Apollon77 commented on packages/common/src/lib/common/tools.ts
> +                `${logNamespace} target for "${sourceId}" not exist for "write" function: "${sourceObj.alias.write}"`
```suggestion
                `${logNamespace}target for "${sourceId}" does not exist for "write" function: "${sourceObj.alias.write}"`
```

2022-12-25 21:04 UTC, foxriver76 approved these changes

2022-12-25 22:32 UTC, merged