allow to choose between verbatim and ipv4 first dns resolution order
ioBroker/ioBroker.js-controller pull request #2120
Opened 2023-03-05 12:44 UTC by foxriver76

- closes #2053

waiting for #2110 before merge

2023-03-05 13:34 UTC, foxriver76 commented
if we want to we can also publish the schema on schemastore for files matching `iobroker.json` any maybe `iobroker-dist.json` also admin could validate against schema. Thoughts? Or maybe there are expected conflicts, so that other files are also often named `iobroker.json`?

2023-03-08 14:19 UTC, Apollon77 commented
maybe then we should alsoi kill nodejs 12 testing at least with this PR?
And I requested changes to  other PR because: >= v16.4.0, v14.18.0

2023-03-08 14:20 UTC, Apollon77 requested changes

2023-03-08 14:20 UTC, Apollon77 commented on packages/common/src/lib/common/tools.ts
> +        dnsOrder = config.dnsResolution;
This will break for all existing installations because it will set "undefined"

2023-03-08 20:38 UTC, Apollon77 approved these changes

2023-03-08 20:39 UTC, Apollon77 commented
Important: Merhing this will break also all nodejs 12 testing ... so we now have Two PRs with this "dep". inform devs and do in some days?

2023-03-13 14:00 UTC, merged