Changed type of ignoreInVersions in visWidgets
ioBroker/ioBroker.js-controller pull request #2629
Opened 2024-03-11 01:39 UTC by GermanBluefox

2024-03-11 06:56 UTC, foxriver76 commented
is it correct like this or recent change? If it was a recent design change, then we should avoid having properties with free chooseable names and fixed names on the same level.

2024-03-12 00:00 UTC, GermanBluefox commented
> is it correct like this or recent change? If it was a recent design change, then we should avoid having properties with free chooseable names and fixed names on the same level.
> 
> Also in the schema it is not on level of visWidgets property but on the level of the individual widgetSet.. so what is now if I want to provide one widget set exclusive for vis1 another exclusive for vis2? This would no longer be configurable..

I changed a bit

2024-03-16 06:46 UTC, foxriver76 requested changes

2024-03-16 06:46 UTC, foxriver76 commented on packages/types-dev/objects.d.ts
> +            visWidgets?: Record<string, VisWidget> | { ignoreInVersions?: number[] };
Now you can either define via widgets or ignore I do not think it is the intention. See also my previous comment.

2024-04-22 06:49 UTC, foxriver76 commented on packages/types-dev/objects.d.ts
> +            visWidgets?: Record<string, VisWidget> | { ignoreInVersions?: number[] };
Okay, please confirm: 

Valid: 
```json
....
"visWidgets": {
    "ignoreInVersions": [2]
}
.... 
```

Valid: 
....
"visWidgets": {
    "mySuperWidget": { ... }
}
.... 
```

Invalid:
....
"visWidgets": {
    "mySuperWidget": { ... },
    "ignoreInVersions": [2]
},
.... 
```

Maybe add some type tests to `types-public` package in `index.test-d.ts` to ensure it works like intended.

2024-08-27 09:43 UTC, foxriver76 commented
as we have discussed in one of the core meetings the schema will stay and implementation should follow it

2024-08-27 09:43 UTC, closed without merging