[typing] Better typing in main.ts
ioBroker/ioBroker.js-controller pull request #2911
Opened 2024-09-14 08:16 UTC by GermanBluefox

Catch potential error in `writeBaseSettings`

Typing for writeBaseSettings/readbaseSettings added

2024-09-19 10:55 UTC, GermanBluefox commented on packages/controller/src/main.ts
> +                    } else {
Changed

2024-09-19 11:17 UTC, Apollon77 approved these changes

2024-09-21 08:40 UTC, foxriver76 requested changes

2024-09-21 08:40 UTC, foxriver76 commented on packages/controller/src/main.ts
> +                        error = `Invalid data for writeBaseSettings ${msg.from}`;
Hm if we don't have an error yet we will always assign one here.. and the invalid data logged is the msg.from attribute? I think something is wrong here

2024-09-21 08:46 UTC, foxriver76 commented on packages/controller/src/main.ts
> +                        error = `Invalid data for writeBaseSettings ${msg.from}`;
Hm okay the logic is okay as it only happens if config is falsy but shouldn't we log the received config then

2024-09-21 09:09 UTC, foxriver76 approved these changes

2024-09-21 11:13 UTC, Apollon77 approved these changes

2024-09-21 11:53 UTC, merged