[typing] Added types to adapter.ts
ioBroker/ioBroker.js-controller pull request #2922
Opened 2024-09-24 10:31 UTC by GermanBluefox

Added some typing to adapter.ts
mostly for 'adapter.systemConfig' (I thought that it is content of 'systetm.config' object)

**Tests**
- [ ] I have added tests to test this feature
- [ ] It is not possible to test this feature

2024-11-13 16:10 UTC, GermanBluefox commented
This PR is really easy to merge and it is manageable

2024-11-13 16:13 UTC, foxriver76 requested changes

2025-01-03 11:31 UTC, GermanBluefox commented on packages/adapter/src/lib/adapter/adapter.ts
> +            return this.#objects!.getObjects(keys, options);
These types are used by admin

2025-01-09 09:48 UTC, foxriver76 commented
https://github.com/ioBroker/ioBroker.js-controller/pull/3001 as there seem to be some inconsistencies with maxQueue, it only affects states DB (used by adapter.ts) not other DBs, hence I removed the dead code to clean this up and move it correctly to states DB only + fix the initial iobroker.json. Just mergeinto your branch  if it is fine for you.

2025-01-09 09:48 UTC, foxriver76 commented
> This PR is really easy to merge and it is manageable

Generally yes but checking in depth then brings up things like now and 1.5 hours go into the land ;-)

2025-01-09 15:15 UTC, foxriver76 approved these changes

2025-01-09 16:24 UTC, merged