[Feature] Do not allow to be active together the stable and beta repositories.
ioBroker/ioBroker.js-controller pull request #2935
Opened 2024-10-03 03:19 UTC by GermanBluefox

- Do not allow to be active together the stable and beta repositories.
- Allow addressing the repositories by index in the table

**Tests**
- [ ] I have added tests to avoid a recursion of this bug
- [x] It is not possible to test for this bug

Only CLI files changed

**Documentation**
- [x] I have documented the new feature

2024-10-04 12:31 UTC, Apollon77 requested changes
What exactly is the point of working with index? This adds a lot of edge cases as you can see in the code you needed to add. In fact you can not assume any order anyway, so what exactly is the point here?

if it gets easier we could also not use a joined parameter "name/index" but use different comands that use index which makes it easier too

2024-10-04 12:56 UTC, foxriver76 approved these changes

2024-10-04 14:31 UTC, GermanBluefox commented on packages/cli/src/lib/setup/setupRepo.ts
> +                if (repoName.toLowerCase().includes('beta')) {
Changed to startsWith

2024-11-10 08:51 UTC, foxriver76 approved these changes

2024-11-17 16:24 UTC, GermanBluefox commented
I still do not understand, If we have index, why not to use it instead of writing "my repo" ?
Same logic is used for backends

2024-11-17 16:33 UTC, foxriver76 commented
> I still do not understand, If we have index, why not to use it instead of writing "my repo" ? Same logic is used for restoring

Hm index is now supported? but of course not for `add` or `addset` just for `set`and `del`, as the index will just be the next free and you cannot specify like 100 out of nowhere. Or what is the problem now?

2024-11-19 12:18 UTC, Apollon77 approved these changes

2024-11-19 12:21 UTC, merged